# **Numpy Basics Cheatsheet by Data Growth Community**
![](https://numpy.org/doc/stable/_static/numpylogo.svg)

**NumPy** es una biblioteca fundamental para la **computación científica en Python**. Proporciona arreglos multidimensionales, rutinas para operaciones rápidas en estos arreglos y objetos derivados como matrices.

El objeto central en NumPy es el **ndarray**, que encapsula arreglos n-dimensionales de datos homogéneos. A diferencia de las listas de Python, los arreglos NumPy tienen un tamaño fijo al crearse y requieren elementos del mismo tipo de datos.
\

En resumen, **NumPy** es esencial para la eficiencia en operaciones matemáticas y científicas en Python.

### Importar NumPy

In [ ]:
import numpy as np

## 1. Creación de arreglos

In [ ]:
# Desde una lista
arr_1d = np.array([1, 2, 3, 4, 5])
print(arr_1d)

[1 2 3 4 5]


In [ ]:
# Desde una lista de listas
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print(arr_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# Arreglo 3D
arr_3d = np.array([[[1, 2], [3, 4]],
                   [[5, 6], [7, 8]]])
print(arr_3d)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### 1.1 Usando funciones auxiliares

In [ ]:
# Crea un arreglo de ceros
arr_zeros = np.zeros(5, dtype=int)
print(arr_zeros)

[0 0 0 0 0]


In [ ]:
# Crea un arreglo de unos
arr_ones = np.ones(3)
print(arr_ones)

[1. 1. 1.]


In [ ]:
# Crea un arreglo de rango
arr_Range = np.arange(10)
print(arr_Range)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# Crea una matriz de ceros
arr_zeros_2d = np.zeros((2, 3), dtype=int)
print(arr_zeros_2d)

[[0 0 0]
 [0 0 0]]


In [ ]:
# Crea una matriz de unos
arr_ones_2d = np.ones((2, 2))
print(arr_ones_2d)

[[1. 1.]
 [1. 1.]]


In [ ]:
# Crear un arreglo con valores espaciados uniformemente
arr_linspace = np.linspace(1, 10, 5)  # [1. 3. 5. 7. 9.]
print(arr_linspace)

[ 1.    3.25  5.5   7.75 10.  ]


In [ ]:
# Crear un arreglo con valores espaciados logarítmicamente
arr_logspace = np.logspace(1, 3, 4)
print(arr_logspace)

[  10.           46.41588834  215.443469   1000.        ]


## 2. Manipulación de arreglos

### Acceder y modificar elementos

In [ ]:
# Acceder a elementos en un arreglo 1D
arr = np.array([1, 2, 3, 4, 5])
print(arr[0])
print(arr[-1])

1
5


In [ ]:
# Acceder a elementos en un arreglo 2D
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print(arr_2d[1, 2])

6


In [ ]:
# Modificar elementos
arr[0] = 10
arr_2d[1, 1] = 0
print(arr)
print(arr_2d)

[10  2  3  4  5]
[[1 2 3]
 [4 0 6]
 [7 8 9]]


### Operaciones aritméticas

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

In [ ]:
# Suma de arreglos
arr_sum = arr1 + arr2
print(arr_sum)

[5 7 9]


In [ ]:
# Multiplicación de arreglos
arr_mul = arr1 * arr2
print(arr_mul)

[ 4 10 18]


### Funciones universales (ufuncs)

In [ ]:
arr = np.array([1, 2, 3, 4])

[1.         1.41421356 1.73205081 2.        ]
[ 2.71828183  7.3890561  20.08553692 54.59815003]


In [ ]:
# Calcular la raíz cuadrada de cada elemento
arr_sqrt = np.sqrt(arr)
print(arr_sqrt)

[1.         1.41421356 1.73205081 2.        ]


In [ ]:
# Aplicar la función exponencial a cada elemento
arr_exp = np.exp(arr)
print(arr_exp)

[ 2.71828183  7.3890561  20.08553692 54.59815003]


### Funciones matemáticas

In [ ]:
arr = np.array([1, 2, 3, 4])

In [ ]:
# Suma de todos los elementos
arr_sum = np.sum(arr)
print(arr_sum)

10


In [ ]:
# Promedio de todos los elementos
arr_mean = np.mean(arr)
print(arr_mean)

2.5


## 3. Operaciones con formas y dimensiones

### Cambiar la forma de un arreglo

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])

In [ ]:
# Cambiar la forma a una matriz 2x3
arr_reshaped = arr.reshape(2, 3)
print(arr_reshaped)

[[1 2 3]
 [4 5 6]]


In [ ]:
# Cambiar la forma a un arreglo 1D
arr_flattened = arr.ravel()
print(arr_flattened)

[1 2 3 4 5 6]


### Transponer arreglos

In [ ]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6]])

In [ ]:
# Transponer la matriz
arr_transposed = arr_2d.T
print(arr_transposed)

[[1 4]
 [2 5]
 [3 6]]


### Operaciones de broadcasting

In [ ]:
# Definimos una matriz 2D
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [ ]:
# Definimos un vector 1D para escalar las columnas
scaling_vector = np.array([1, 0.5, 0.1])

# Broadcasting de un vector 1D a cada columna de la matriz
scaled_matrix = matrix * scaling_vector

print(scaled_matrix)

[[1.  1.  0.3]
 [4.  2.5 0.6]
 [7.  4.  0.9]]


## Indexación y selección de datos

### Indexación básica

In [ ]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [ ]:
# Acceder a una fila específica
print(arr_2d[1])

[4 5 6]


In [ ]:
# Acceder a una columna específica
print(arr_2d[:, 2])

[3 6 9]


### Indexación avanzada

In [ ]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [ ]:
# Acceder a elementos específicos
print(arr_2d[[0, 1], [0, 2]])

[1 6]


In [ ]:
# Acceder a filas y columnas específicas
print(arr_2d[[0, 2], :])

[[1 2 3]
 [7 8 9]]


In [ ]:
# Acceder a una submatriz
submatriz = arr_2d[0:2, 0:2]
print(submatriz)

[[1 2]
 [4 5]]


### Indexación booleana

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])

# Filtrar elementos que cumplen una condición
condition = arr > 3
print(arr[condition])

[4 5 6]


### Fancy Index

In [ ]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
indices = [0, 2]

# Acceder a filas específicas
print(arr_2d[indices])

[[1 2 3]
 [7 8 9]]


## Álgebra lineal

### Operaciones algebraicas básicas

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

In [ ]:
# Producto escalar (dot product)
scalar_prod = np.dot(arr1, arr2)
print(scalar_prod)

32


In [ ]:
# Producto vectorial (cross product)
vector_prod = np.cross(arr1, arr2)
print(vector_prod)

[-3  6 -3]


### Producto de matrices

In [ ]:
mat1 = np.array([[1, 2], [3, 4]])
mat2 = np.array([[5, 6], [7, 8]])

# Multiplicación de matrices
mat_prod = np.matmul(mat1, mat2)
print(mat_prod)

[[19 22]
 [43 50]]


### Cálculo de valores y vectores propios


In [ ]:
mat = np.array([[1, 2], [3, 4]])

In [ ]:
# Valores y vectores propios
eigenvalues, eigenvectors = np.linalg.eig(mat)
print(eigenvalues)

[-0.37228132  5.37228132]


In [ ]:
print(eigenvectors)

[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


## Entrada/Salida y manipulación de archivos

### Lectura y escritura de archivos

In [ ]:
# Guardar un arreglo en un archivo binario
arr = np.array([[1, 2, 3], [4, 5, 6]])
np.save('datos.npy', arr)

# Cargar un arreglo desde un archivo binario
arr_loaded = np.load('datos.npy')
print(arr_loaded)

[[1 2 3]
 [4 5 6]]


### Lectura de datos desde archivos de texto


NumPy proporciona la función `genfromtxt` que permite leer fácilmente datos desde archivos de texto (como archivos CSV, TSV, etc.).

In [ ]:
data = np.genfromtxt('datos.csv', delimiter=',')

*   `genfromtxt` lee los datos del archivo especificado y los convierte en un array de NumPy.
*   El argumento `delimiter` especifica el carácter delimitador utilizado en el archivo de texto (por ejemplo, coma `,` para archivos CSV).

**Opciones adicionales:**
*   `skip_header`: Permite omitir un número específico de líneas al inicio del archivo (útil para archivos con encabezados).
*  ` dtype`: Especifica el tipo de datos de los elementos del array resultante.
*   `missing_values`: Indica cómo manejar los valores faltantes en el archivo.

Esta función es muy útil para cargar datos desde archivos de texto en un formato compatible con NumPy, lo que facilita su posterior procesamiento y análisis

In [ ]:
data = np.genfromtxt('datos.csv', delimiter=',', skip_header=1, dtype=int)

## Estadísticas y análisis de datos

### Funciones estadísticas

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

In [ ]:
# Media
mean = np.mean(arr)
print(mean)

3.0


In [ ]:
# Desviación estándar
std = np.std(arr)
print(std)

1.4142135623730951


### Ordenamiento y búsqueda


In [ ]:
arr = np.array([5, 2, 7, 1, 8, 3])

In [ ]:
# Ordenar el arreglo
sorted_arr = np.sort(arr)
print(sorted_arr)

[1 2 3 5 7 8]


In [ ]:
# Buscar el índice de un valor específico
index = np.searchsorted(sorted_arr, 7)
print(index)

4


### Operaciones con datos faltantes

In [ ]:
arr = np.array([1, 2, np.nan, 4, 5])

In [ ]:
# Detectar valores faltantes
print(np.isnan(arr))

[False False  True False False]


In [ ]:
# Eliminar valores faltantes
arr_cleaned = arr[~np.isnan(arr)]
print(arr_cleaned)

[1. 2. 4. 5.]


### Funciones de estadística

In [ ]:
data = np.array([1, 2, 3, 4, 5])

In [ ]:
# Percentiles
percentiles = np.percentile(data, [25, 50, 75])
print(percentiles)  # [ 2.  3.  4.]

[2. 3. 4.]


In [ ]:
# Distribución normal
from scipy.stats import norm
mu, sigma = 0, 1  # media y desviación estándar
x = np.linspace(-3, 3, 100)
y = norm.pdf(x, mu, sigma)
print(y)  # Densidad de probabilidad de la distribución normal

[0.00443185 0.00530579 0.00632878 0.00752133 0.00890582 0.0105065
 0.01234943 0.01446241 0.01687483 0.01961746 0.02272223 0.02622189
 0.03014961 0.03453857 0.03942137 0.0448295  0.05079264 0.05733801
 0.06448952 0.07226707 0.08068571 0.08975477 0.09947714 0.10984842
 0.12085626 0.13247967 0.14468855 0.15744319 0.17069405 0.18438164
 0.1984366  0.21277993 0.22732351 0.24197072 0.2566174  0.27115285
 0.28546117 0.29942268 0.31291556 0.3258175  0.33800759 0.34936814
 0.35978656 0.36915722 0.37738323 0.38437808 0.3900672  0.39438923
 0.39729716 0.39875915 0.39875915 0.39729716 0.39438923 0.3900672
 0.38437808 0.37738323 0.36915722 0.35978656 0.34936814 0.33800759
 0.3258175  0.31291556 0.29942268 0.28546117 0.27115285 0.2566174
 0.24197072 0.22732351 0.21277993 0.1984366  0.18438164 0.17069405
 0.15744319 0.14468855 0.13247967 0.12085626 0.10984842 0.09947714
 0.08975477 0.08068571 0.07226707 0.06448952 0.05733801 0.05079264
 0.0448295  0.03942137 0.03453857 0.03014961 0.02622189 0.0227222

## Funciones especiales
### Funciones de procesamiento de señales

In [ ]:
# Convolución de dos arreglos 1D
data1 = np.array([1, 2, 3])
data2 = np.array([4, 5])
result = np.convolve(data1, data2, mode='full')
print(result)  # [ 4 13 22 15  3]

# Transformada de Fourier
signal = np.array([1, 2, 3, 4])
fourier_transform = np.fft.fft(signal)
print(fourier_transform)
# [ 10.00000000e+00 -1.08166817e-15 +2.22044605e-16j
#    2.22044605e-16 +1.08166817e-15j]

[ 4 13 22 15]
[10.+0.j -2.+2.j -2.+0.j -2.-2.j]


### Funciones de álgebra lineal

In [ ]:
mat = np.array([[1, 2], [3, 4]])

# Calcular la matriz inversa
inv_mat = np.linalg.inv(mat)
print(inv_mat)
# [[-2.   1. ]
#  [ 1.5 -0.5]]

# Resolver un sistema de ecuaciones lineales
A = np.array([[1, 2], [3, 4]])
b = np.array([5, 11])
x = np.linalg.solve(A, b)
print(x)  # [ 1. 2.]

[[-2.   1. ]
 [ 1.5 -0.5]]
[1. 2.]


### Funciones de estadística

In [ ]:
data = np.array([1, 2, 3, 4, 5])

# Percentiles
percentiles = np.percentile(data, [25, 50, 75])
print(percentiles)

# Distribución normal
from scipy.stats import norm
mu, sigma = 0, 1  # media y desviación estándar
x = np.linspace(-3, 3, 100)
y = norm.pdf(x, mu, sigma)
print(y)  # Densidad de probabilidad de la distribución normal

[2. 3. 4.]
[0.00443185 0.00530579 0.00632878 0.00752133 0.00890582 0.0105065
 0.01234943 0.01446241 0.01687483 0.01961746 0.02272223 0.02622189
 0.03014961 0.03453857 0.03942137 0.0448295  0.05079264 0.05733801
 0.06448952 0.07226707 0.08068571 0.08975477 0.09947714 0.10984842
 0.12085626 0.13247967 0.14468855 0.15744319 0.17069405 0.18438164
 0.1984366  0.21277993 0.22732351 0.24197072 0.2566174  0.27115285
 0.28546117 0.29942268 0.31291556 0.3258175  0.33800759 0.34936814
 0.35978656 0.36915722 0.37738323 0.38437808 0.3900672  0.39438923
 0.39729716 0.39875915 0.39875915 0.39729716 0.39438923 0.3900672
 0.38437808 0.37738323 0.36915722 0.35978656 0.34936814 0.33800759
 0.3258175  0.31291556 0.29942268 0.28546117 0.27115285 0.2566174
 0.24197072 0.22732351 0.21277993 0.1984366  0.18438164 0.17069405
 0.15744319 0.14468855 0.13247967 0.12085626 0.10984842 0.09947714
 0.08975477 0.08068571 0.07226707 0.06448952 0.05733801 0.05079264
 0.0448295  0.03942137 0.03453857 0.03014961 0.0262218

### Correlación entre dos arreglos

In [ ]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([5, 4, 3, 2, 1])
corr = np.corrcoef(arr1, arr2)
print(corr)



[[ 1. -1.]
 [-1.  1.]]


### Covarianza entre dos arreglos


In [ ]:
cov = np.cov(arr1, arr2)
print(cov)

[[ 2.5 -2.5]
 [-2.5  2.5]]


## Copias de Arrays
En NumPy, existen diferentes formas de crear copias de arrays, y es importante comprender la diferencia entre ellas.



### Vista (View)
Una vista es una forma de acceder a los mismos datos del array original. Modificar la vista también modifica el array original.



In [ ]:
arr = np.array([1, 2, 3, 4])
view_arr = arr.view()
view_arr[0] = 9
print(arr)


[9 2 3 4]


In [ ]:
print(view_arr)

[9 2 3 4]


### Copia profunda (Deep Copy)
Una copia profunda crea un nuevo array con una nueva ubicación de memoria, independiente del array original. Modificar la copia no afecta al array original.

In [ ]:
arr = np.array([1, 2, 3, 4])
deep_copy_arr = arr.copy()
deep_copy_arr[0] = 9
print(arr)

[1 2 3 4]


In [ ]:
print(deep_copy_arr)

[9 2 3 4]


### Copia superficial (Shallow Copy)
Una copia superficial crea una nueva vista del array original, pero cualquier cambio en los elementos anidados (como matrices dentro de matrices) afectará tanto a la copia como al original.

In [ ]:
arr = np.array([[1, 2], [3, 4]])
shallow_copy_arr = arr.view()
shallow_copy_arr[0, 0] = 9
print(arr)

[[9 2]
 [3 4]]


In [ ]:
print(shallow_copy_arr)

[[9 2]
 [3 4]]


## Descomposición en Valores Singulares (SVD)
La descomposición en valores singulares (SVD, por sus siglas en inglés) es un método muy útil en álgebra lineal numérica. En NumPy, la función `numpy.linalg.svd` se utiliza para calcular la SVD de una matriz.


La SVD tiene diversas aplicaciones en álgebra lineal numérica, como la resolución de sistemas de ecuaciones lineales, cálculo de pseudo-inversas, compresión de datos, entre otras.


In [ ]:
# Crear una matriz
A = np.array([[1, 2], [3, 4]])

# Calcular la SVD
U, s, Vh = np.linalg.svd(A)

print("Matriz original:")
print(A)
print("\nMatrices de la descomposición SVD:")
print("U:\n", U)
print("Valores singulares:\n", s)
print("V^H:\n", Vh)

Matriz original:
[[1 2]
 [3 4]]

Matrices de la descomposición SVD:
U:
 [[-0.40455358 -0.9145143 ]
 [-0.9145143   0.40455358]]
Valores singulares:
 [5.4649857  0.36596619]
V^H:
 [[-0.57604844 -0.81741556]
 [ 0.81741556 -0.57604844]]


**Explicación:**


*   La descomposición SVD de una matriz `A` se representa como: `A = U * np.diag(s) * Vh`, donde `U` y `Vh` son matrices ortogonales, y `s` contiene los valores singulares (escalares) de `A`.
*   `U` y `Vh` son las matrices de vectores singulares izquierdos y derechos, respectivamente.
*   `s` contiene los valores singulares de `A` ordenados de forma descendente.






## Funciones especiales



### Funciones de procesamiento de señales


In [ ]:
# Convolución de dos arreglos 1D
data1 = np.array([1, 2, 3])
data2 = np.array([4, 5])
result = np.convolve(data1, data2, mode='full')
print(result)


[ 4 13 22 15]


In [ ]:
# Transformada de Fourier
signal = np.array([1, 2, 3, 4])
fourier_transform = np.fft.fft(signal)
print(fourier_transform)

[10.+0.j -2.+2.j -2.+0.j -2.-2.j]


### Funciones de álgebra lineal

In [ ]:
mat = np.array([[1, 2], [3, 4]])

In [ ]:
# Calcular la matriz inversa
inv_mat = np.linalg.inv(mat)
print(inv_mat)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
# Resolver un sistema de ecuaciones lineales
A = np.array([[1, 2], [3, 4]])
b = np.array([5, 11])
x = np.linalg.solve(A, b)
print(x)

[1. 2.]


### Operaciones de máscara y compresión

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

In [ ]:
# Máscara
mask = arr > 3
print(arr[mask])

[4 5]


In [ ]:
# Compresión
compressed_arr = np.compress([True, False, True, True, False], arr)
print(compressed_arr)

[1 3 4]
